pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/jenkins1/my-app") {
                sh "mvn -Dmaven.test.failure.ignore=true clean package"                }
            }
        }
     
    }
post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
