pipeline {
    agent any
    stages {
        stage('deploy') {
            steps {
                dir("/var/lib/jenkins/workspace/works_free/my-app"){
                sh "docker build -t newimage:2.0 ."
                sh "docker run -d -p 8081:8081 newimage:2.0"
            }
            }
        }

    }
}
